#Makefile for the curses system.
#Called during kernel compilation, provided that we have added the curse source folder in the kernel makefile.

EXTRA_CFLAGS+=-Werror -Wuninitialized
obj-y	:= curse.o no_fs_cache.o

# TODO: Add invocation to curse makefile (the one that compiles the available curses).

